name: Submit existing Near build

on:
  workflow_dispatch:
    inputs:
      build_id:
        type: string
        required: true
        description: EAS iOS build ID to upload to TestFlight.

jobs:
  submit_ios:
    name: Upload existing build to TestFlight
    type: submit
    params:
      build_id: ${{ inputs.build_id }}
      profile: production
